[project]
name = "aiagentscourse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.5",
    "async-timeout>=5.0.1",
    "beautifulsoup4>=4.14.3",
    "gradio>=6.2.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "lxml>=6.1.0",
    "openai>=2.14.0",
    "openai-agents[litellm]>=0.8.4",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.2.1",
    "readability-lxml>=0.8.4.1",
]
